name         'vladgh-common'
version      '1.0.0'
author       'Vlad Ghinea'
license      'Apache 2.0'
summary      'This module adds common functions to the catalog.'
description  'This module adds common functions to the catalog.'
source       'https://github.com/vladgh/puppet-module-common'
project_page 'https://github.com/vladgh/puppet-module-common'

dependency   'puppetlabs-stdlib', '>= 2.3.1'
